version: '3'
services:
  postgresql:
    image: postgres:alpine
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: shi
      POSTGRES_PASSWORD: s#nd0#B9@iW5
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      
volumes:
  db-store: